name: Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.22.1'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Test project
      run: flutter test
    
    - name: Build release project
      run: flutter build web

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build/web

    - name: List files in build directory
      run: ls -la ./build/web
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Check Firebase CLI version
      run: firebase --version
    
    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only hosting